# Generated by Django 5.1.7 on 2025-03-23 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0007_alter_tickettype_price'),
        ('tickets', '0003_tickettype_name_alter_tickettype_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_ticket_types', to='concerts.concert'),
        ),
    ]
