# Generated by Django 5.1.7 on 2025-03-23 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0009_remove_concert_ticket_types_delete_tickettype'),
        ('tickets', '0005_alter_tickettype_concert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='concerts.concert'),
        ),
    ]
