# Generated by Django 5.1.7 on 2025-03-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
