# Generated by Django 5.1.7 on 2025-03-23 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_concert_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='ar_model',
            field=models.FileField(blank=True, null=True, upload_to='ar_models/'),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_ticket_types', to='concerts.concert')),
            ],
        ),
    ]
