# Generated by Django 5.1.7 on 2025-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_alter_concert_ar_model_tickettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='category',
            field=models.CharField(choices=[('VIP', 'VIP (200 pax)'), ('LB', 'Lower Box (500 pax)'), ('UB', 'Upper Box (800 pax)'), ('GA', 'General Admission (1500 pax)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
