# Generated by Django 5.1.7 on 2025-03-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0005_tickettype_total_quantity_alter_tickettype_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
