# Generated by Django 5.1.7 on 2025-03-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0006_alter_tickettype_remaining_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
