# Generated by Django 5.1.7 on 2025-03-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0008_concert_ticket_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='ticket_types',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
